#!/usr/bin/env bash
#!nix-shell -i bash -p yt-dlp

# Download the audio by passing the url as a parameter. Quite useful to download audio from Youtube.
# You'll need to install this: https://github.com/yt-dlp/yt-dlp/

yt-dlp -f bestaudio -x --audio-format alac --audio-quality 0 -N 8 "$1"
